### ISSUE TITLE
Error cooking Orchard due to DNS error for packages.orchardproject.net

### ISSUE THREAD

**Issue by mroskamp** [OrchardCMS/Orchard.Gallery#32]
We have several Orchard sites that we re-cook nightly. The cooks have started failing recently. The failures appear to be related to being unable to connect to the Orchard gallery to download dependent modules.

When I browse to packages.orchardproject.net in a web browser, I get a DNS error.

I see on the Orchard gallery that there's reference to a new version of the Gallery, and a new FeedService address, but it also mentions that the old URL should continue working.

```
2016-10-20 22:47:44,799 [1] Orchard.Recipes.Services.RecipeStepExecutor - (null) - Recipe execution bc8bfa7c64d842b996535272f2e7f2b8 was cancelled because a step failed to execute
 (null)
System.Net.WebException: The remote name could not be resolved: 'packages.orchardproject.net'
   at System.Net.HttpWebRequest.GetResponse()
   at System.Data.Services.Client.QueryResult.Execute()
   at System.Data.Services.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   at System.Data.Services.Client.DataServiceQuery`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Orchard.Packaging.Services.PackagingSourceManager.GetExtensionListFromSource(Boolean includeScreenshots, PackagingSource packagingSource, Func`2 query, PackagingSource source)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Orchard.Recipes.RecipeHandlers.ModuleRecipeHandler.ExecuteRecipeStep(RecipeContext recipeContext)
   at Orchard.Recipes.Services.RecipeStepExecutor.ExecuteNextStep(String executionId)
2016-10-20 22:47:45,059 [1] Orchard.Exceptions.DefaultExceptionPolicy - (null) - An unexpected exception was caught
 (null)
Orchard.OrchardCoreException: Recipe execution with id bc8bfa7c64d842b996535272f2e7f2b8 was cancelled because the "Module" step failed to execute. The following exception was thrown: The remote name could not be resolved: &#39;packages.orchardproject.net&#39;. Refer to the error logs for more information.
   at Orchard.Recipes.Services.RecipeStepExecutor.ExecuteNextStep(String executionId)
   at Orchard.Recipes.Services.RecipeScheduler.ExecuteWork(String executionId)
   at Orchard.Events.DelegateHelper.<>c__DisplayClass14_0`2.<BuildAction>b__0(Object target, Object[] p) in C:\Builds\25\Advantage\Cider-Hippo\src\Work\src\Orchard\Events\DelegateHelper.cs:line 116
   at Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(IEventHandler eventHandler, Type interfaceType, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) in C:\Builds\25\Advantage\Cider-Hippo\src\Work\src\Orchard\Events\DefaultOrchardEventBus.cs:line 82
   at Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue) in C:\Builds\25\Advantage\Cider-Hippo\src\Work\src\Orchard\Events\DefaultOrchardEventBus.cs:line 53
```

**Comment by mroskamp** [comment]
Quick update on this: I manually changed the that package source (following [this changeset](https://github.com/OrchardCMS/Orchard/commit/9da248871f4101f4f974c93a48237d36ffb9947d)). I no longer the `The remote name could not be resolved: 'packages.orchardproject.net'` error, but now cooking the recipe seems to fail downloading the package from the new gallery:

`2016-10-25 09:50:04,561 [1] Orchard.Recipes.Services.RecipeStepExecutor - (null) - Recipe execution ad4f2a2bc1fa432aa0a671021671f6c2 was cancelled because a step failed to execute
 (null)
System.InvalidOperationException: Could not enable feature Devq.ErrorLog because it was not found.
   at Orchard.Recipes.RecipeHandlers.FeatureRecipeHandler.ExecuteRecipeStep(RecipeContext recipeContext)
   at Orchard.Recipes.Services.RecipeStepExecutor.ExecuteNextStep(String executionId)
2016-10-25 09:50:04,708 [1] Orchard.Exceptions.DefaultExceptionPolicy - (null) - An unexpected exception was caught
 (null)
Orchard.OrchardCoreException: Recipe execution with id ad4f2a2bc1fa432aa0a671021671f6c2 was cancelled because the "Feature" step failed to execute. The following exception was thrown: Could not enable feature Devq.ErrorLog because it was not found.. Refer to the error logs for more information.
   at Orchard.Recipes.Services.RecipeStepExecutor.ExecuteNextStep(String executionId)
   at Orchard.Recipes.Services.RecipeScheduler.ExecuteWork(String executionId)
   at Orchard.Events.DelegateHelper.<>c__DisplayClass14_0`2.<BuildAction>b__0(Object target, Object[] p) in C:\tf\advantage\Features\flamingo\Cider\src\Orchard\Events\DelegateHelper.cs:line 116
   at Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(IEventHandler eventHandler, Type interfaceType, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) in C:\tf\advantage\Features\flamingo\Cider\src\Orchard\Events\DefaultOrchardEventBus.cs:line 84
   at Orchard.Events.DefaultOrchardEventBus.TryInvoke(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) in C:\tf\advantage\Features\flamingo\Cider\src\Orchard\Events\DefaultOrchardEventBus.cs:line 70
   at Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue) in C:\tf\advantage\Features\flamingo\Cider\src\Orchard\Events\DefaultOrchardEventBus.cs:line 53
`

**Comment by sebastienros** [comment]
Can you file an issue on the Orchard repos? It's maybe an issue with the `enable feature` step.

**Comment by mroskamp** [comment]
Yes, I'll log the issue there.

Disregarding the recipe issue, after manually changing the FeedSource in the DefaultPackagingUpdater to point at `https://gallery.orchardproject.net/api/FeedService`, Orchard is now able to connect to the gallery and install packages.

I think fixing the redirect between the old and new galleries would solve this issue.

(also note that the gallery website has the outdated https://orchardgallery.azurewebsites.net/api/FeedService URL on the homepage)

**Comment by sebastienros** [comment]
Can you provide a PR with the fix you are suggesting? Thanks

**Comment by mroskamp** [comment]
There's isn't a PR, as the current version of Orchard already has a fix in [this changeset](https://github.com/OrchardCMS/Orchard/commit/9da248871f4101f4f974c93a48237d36ffb9947d).

However, we're running Orchard v1.9.2, which still has the old package source (`http://packages.orchardproject.net/FeedService.svc`) hardcoded. I would expect this old package source to redirect to the new one, otherwise the gallery is unusable for anyone running an older version of Orchard.

Additionally, the [new Gallery website](http://gallery.orchardproject.net/) states that the old feed URL would be redirected, which seems to be incorrect, based on what I'm seeing.

![2016-10-25_1409](https://cloud.githubusercontent.com/assets/4029047/19698334/dedffcaa-9abc-11e6-9b26-8db807a823a0.png)

**Comment by sebastienros** [comment]
Makes sense, I thought we had that already. Will check.

**Comment by sebastienros** [comment]
@agriffard haven't you made this redirection already?

**Comment by sebastienros** [comment]
There is currently a widespread DNS issue on the internet. It's not just
Orchard, for instance i can't even reach GitHub personally.

**Comment by mroskamp** [comment]
Thanks @sebastienros, I was aware of the DNS issues, but thought they had been resolved over the weekend.

**Comment by sebastienros** [comment]
Sorry, this is an answer I gave a few days ago, that never left my inbox, until I opened Outlook from my desktop ;)

**Comment by agriffard** [comment]
The new url is https://gallery.orchardproject.net/api/FeedService

**Comment by mroskamp** [comment]
@agriffard I changed my site (running v1.9.2) to point at the new URL a few days ago and that does work.

Does this mean that the gallery will be unusable for everyone running an older version of Orchard, unless they Gallery settings? Or, will the old URL be redirected to the new one, as mentioned on the gallery site (seen above)?

**Comment by sebastienros** [comment]
Checking for a redirect right now
